import Head from "next/head";
import About from "../components/About";
import Expertise from "../components/Expertise";
import Hero from "../components/Hero";
import Newsletter from "../components/Newsletter";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Rohit Sahani - UI/UX Designer & Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>

      {/* Hero Section */}
      <Hero />

      {/* About Section */}
      <About />

      {/* Expertise Section */}
      <Expertise />

      {/* Newsletter Section */}
      <Newsletter />

      {/* Project Section */}
      <Projects />
    </div>
  );
}
